Index: logs/dbt.log
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.BaseRevisionTextPatchEP
<+>\u001B[0m16:17:43.904989 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x111f5a150>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x111591820>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1115918b0>]}\n\n\n============================== 16:17:43.910893 | 16dba203-c7e6-4535-acc5-8d1706627327 ==============================\n\u001B[0m16:17:43.910893 [info ] [MainThread]: Running with dbt=1.9.3\n\u001B[0m16:17:43.911237 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': '/Users/insider/.dbt', 'fail_fast': 'False', 'version_check': 'True', 'log_path': 'logs', 'debug': 'False', 'warn_error': 'None', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'None', 'log_format': 'default', 'introspect': 'True', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'static_parser': 'True', 'target_path': 'None', 'invocation_command': 'dbt init', 'send_anonymous_usage_stats': 'True'}\n\u001B[0m16:18:11.302565 [debug] [MainThread]: Starter project path: /Users/insider/Documents/InsiderProjects/dbtCCMS/.venv/lib/python3.12/site-packages/dbt/include/starter_project\n\u001B[0m16:18:11.316517 [info ] [MainThread]: \nYour new dbt project \"transformations_ccms\" was created!\n\nFor more information on how to configure the profiles.yml file,\nplease consult the dbt documentation here:\n\n  https://docs.getdbt.com/docs/configure-your-profile\n\nOne more thing:\n\nNeed help? Don't hesitate to reach out to us via GitHub issues or on Slack:\n\n  https://community.getdbt.com/\n\nHappy modeling!\n\n\u001B[0m16:18:11.316870 [info ] [MainThread]: Setting up your profile.\n\u001B[0m16:18:53.917810 [info ] [MainThread]: Profile transformations_ccms written to /Users/insider/.dbt/profiles.yml using target's profile_template.yml and your supplied values. Run 'dbt debug' to validate the connection.\n\u001B[0m16:18:53.933908 [debug] [MainThread]: Resource report: {\"command_name\": \"init\", \"command_success\": true, \"command_wall_clock_time\": 70.25257, \"process_in_blocks\": \"0\", \"process_kernel_time\": 0.462322, \"process_mem_max_rss\": \"180289536\", \"process_out_blocks\": \"0\", \"process_user_time\": 1.276837}\n\u001B[0m16:18:53.935274 [debug] [MainThread]: Command `dbt init` succeeded at 16:18:53.934872 after 70.26 seconds\n\u001B[0m16:18:53.936372 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x111c830e0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1048faab0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x131b132f0>]}\n\u001B[0m16:18:53.937085 [debug] [MainThread]: Flushing usage events\n\u001B[0m16:18:55.128849 [debug] [MainThread]: An error was encountered while trying to flush usage events\n\u001B[0m18:27:56.005440 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x105862780>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x105191220>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1051916a0>]}\n\n\n============================== 18:27:56.018990 | 7bda2943-c914-4f28-931e-dc396027569a ==============================\n\u001B[0m18:27:56.018990 [info ] [MainThread]: Running with dbt=1.9.3\n\u001B[0m18:27:56.019396 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': '/Users/insider/.dbt', 'fail_fast': 'False', 'version_check': 'True', 'log_path': 'logs', 'warn_error': 'None', 'debug': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'False', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'introspect': 'True', 'static_parser': 'True', 'log_format': 'default', 'target_path': 'None', 'invocation_command': 'dbt run --select logs transformations_ccms from briefings', 'send_anonymous_usage_stats': 'True'}\n\u001B[0m18:27:56.019756 [error] [MainThread]: Encountered an error:\nRuntime Error\n  No dbt_project.yml found at expected path /Users/insider/Documents/InsiderProjects/dbtCCMS/dbt_project.yml\n  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml\n  \n\u001B[0m18:27:56.158247 [debug] [MainThread]: Resource report: {\"command_name\": \"run\", \"command_success\": false, \"command_wall_clock_time\": 0.26507545, \"process_in_blocks\": \"0\", \"process_kernel_time\": 0.528571, \"process_mem_max_rss\": \"92356608\", \"process_out_blocks\": \"0\", \"process_user_time\": 1.515957}\n\u001B[0m18:27:56.158950 [debug] [MainThread]: Command `dbt run` failed at 18:27:56.158819 after 0.27 seconds\n\u001B[0m18:27:56.159439 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x105b975f0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x106035d60>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x106035df0>]}\n\u001B[0m18:27:56.159865 [debug] [MainThread]: Flushing usage events\n\u001B[0m18:27:57.569634 [debug] [MainThread]: An error was encountered while trying to flush usage events\n\u001B[0m18:30:35.784114 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x107ebbef0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x107c6d8e0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x107c6d8b0>]}\n\n\n============================== 18:30:35.787456 | 27e8b367-d815-4b75-9666-85b94d0cbfef ==============================\n\u001B[0m18:30:35.787456 [info ] [MainThread]: Running with dbt=1.9.3\n\u001B[0m18:30:35.787757 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': '/Users/insider/.dbt', 'fail_fast': 'False', 'warn_error': 'None', 'log_path': 'logs', 'version_check': 'True', 'debug': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'False', 'quiet': 'False', 'no_print': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'static_parser': 'True', 'log_format': 'default', 'invocation_command': 'dbt run --select logs transformations_ccms from briefings', 'target_path': 'None', 'introspect': 'True', 'send_anonymous_usage_stats': 'True'}\n\u001B[0m18:30:35.788040 [error] [MainThread]: Encountered an error:\nRuntime Error\n  No dbt_project.yml found at expected path /Users/insider/Documents/InsiderProjects/dbtCCMS/dbt_project.yml\n  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml\n  \n\u001B[0m18:30:35.789673 [debug] [MainThread]: Resource report: {\"command_name\": \"run\", \"command_success\": false, \"command_wall_clock_time\": 0.06507084, \"process_in_blocks\": \"0\", \"process_kernel_time\": 0.158809, \"process_mem_max_rss\": \"92258304\", \"process_out_blocks\": \"0\", \"process_user_time\": 0.623294}\n\u001B[0m18:30:35.789893 [debug] [MainThread]: Command `dbt run` failed at 18:30:35.789840 after 0.07 seconds\n\u001B[0m18:30:35.790060 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x108094fe0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x107ebbef0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x10876e8a0>]}\n\u001B[0m18:30:35.790209 [debug] [MainThread]: Flushing usage events\n\u001B[0m18:30:36.365187 [debug] [MainThread]: An error was encountered while trying to flush usage events\n\u001B[0m19:16:06.727498 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1036ce060>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x103f55a60>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x103f559d0>]}\n\n\n============================== 19:16:06.731037 | 160a6c38-7e11-4f94-9700-ef8df0456150 ==============================\n\u001B[0m19:16:06.731037 [info ] [MainThread]: Running with dbt=1.9.3\n\u001B[0m19:16:06.731407 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': '/Users/insider/.dbt', 'fail_fast': 'False', 'version_check': 'True', 'log_path': 'logs', 'debug': 'False', 'warn_error': 'None', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'False', 'quiet': 'False', 'no_print': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'invocation_command': 'dbt run --select logs transformations_ccms from staging_briefings', 'log_format': 'default', 'static_parser': 'True', 'target_path': 'None', 'introspect': 'True', 'send_anonymous_usage_stats': 'True'}\n\u001B[0m19:16:06.731725 [error] [MainThread]: Encountered an error:\nRuntime Error\n  No dbt_project.yml found at expected path /Users/insider/Documents/InsiderProjects/dbtCCMS/dbt_project.yml\n  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml\n  \n\u001B[0m19:16:06.733213 [debug] [MainThread]: Resource report: {\"command_name\": \"run\", \"command_success\": false, \"command_wall_clock_time\": 0.067751125, \"process_in_blocks\": \"0\", \"process_kernel_time\": 0.174925, \"process_mem_max_rss\": \"91521024\", \"process_out_blocks\": \"0\", \"process_user_time\": 0.623211}\n\u001B[0m19:16:06.733483 [debug] [MainThread]: Command `dbt run` failed at 19:16:06.733427 after 0.07 seconds\n\u001B[0m19:16:06.733679 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1048df290>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x10468a900>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1036ce060>]}\n\u001B[0m19:16:06.733852 [debug] [MainThread]: Flushing usage events\n\u001B[0m19:16:07.299284 [debug] [MainThread]: An error was encountered while trying to flush usage events\n\u001B[0m19:16:45.652119 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x106187aa0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1074a4740>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1074a4c80>]}\n\n\n============================== 19:16:45.655645 | 2fd5d7d1-e564-448c-be16-ee74415cd38b ==============================\n\u001B[0m19:16:45.655645 [info ] [MainThread]: Running with dbt=1.9.3\n\u001B[0m19:16:45.655956 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': '/Users/insider/.dbt', 'version_check': 'True', 'debug': 'False', 'log_path': 'logs', 'warn_error': 'None', 'fail_fast': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'False', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'invocation_command': 'dbt run --select logs transformations_ccms from staging_briefings', 'static_parser': 'True', 'log_format': 'default', 'target_path': 'None', 'introspect': 'True', 'send_anonymous_usage_stats': 'True'}\n\u001B[0m19:16:45.656269 [error] [MainThread]: Encountered an error:\nRuntime Error\n  No dbt_project.yml found at expected path /Users/insider/Documents/InsiderProjects/dbtCCMS/dbt_project.yml\n  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml\n  \n\u001B[0m19:16:45.657703 [debug] [MainThread]: Resource report: {\"command_name\": \"run\", \"command_success\": false, \"command_wall_clock_time\": 0.06661679, \"process_in_blocks\": \"0\", \"process_kernel_time\": 0.154808, \"process_mem_max_rss\": \"92520448\", \"process_out_blocks\": \"0\", \"process_user_time\": 0.6209}\n\u001B[0m19:16:45.657929 [debug] [MainThread]: Command `dbt run` failed at 19:16:45.657879 after 0.07 seconds\n\u001B[0m19:16:45.658115 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x106187aa0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1074a58e0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1077550a0>]}\n\u001B[0m19:16:45.658260 [debug] [MainThread]: Flushing usage events\n\u001B[0m19:16:46.228890 [debug] [MainThread]: An error was encountered while trying to flush usage events\n\u001B[0m20:14:08.650458 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x105e737a0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x10586da90>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x10586da00>]}\n\n\n============================== 20:14:08.654489 | f042a257-a509-42a8-931e-c9948316f16f ==============================\n\u001B[0m20:14:08.654489 [info ] [MainThread]: Running with dbt=1.9.3\n\u001B[0m20:14:08.654803 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': '/Users/insider/.dbt', 'version_check': 'True', 'debug': 'False', 'log_path': 'logs', 'fail_fast': 'False', 'warn_error': 'None', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'False', 'quiet': 'False', 'no_print': 'None', 'log_format': 'default', 'static_parser': 'True', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'introspect': 'True', 'target_path': 'None', 'invocation_command': 'dbt run --select logs transformations_ccms from staging_briefings', 'send_anonymous_usage_stats': 'True'}\n\u001B[0m20:14:08.655115 [error] [MainThread]: Encountered an error:\nRuntime Error\n  No dbt_project.yml found at expected path /Users/insider/Documents/InsiderProjects/dbtCCMS/dbt_project.yml\n  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml\n  \n\u001B[0m20:14:08.656586 [debug] [MainThread]: Resource report: {\"command_name\": \"run\", \"command_success\": false, \"command_wall_clock_time\": 0.065566085, \"process_in_blocks\": \"0\", \"process_kernel_time\": 0.158894, \"process_mem_max_rss\": \"93323264\", \"process_out_blocks\": \"0\", \"process_user_time\": 0.654141}\n\u001B[0m20:14:08.656823 [debug] [MainThread]: Command `dbt run` failed at 20:14:08.656768 after 0.07 seconds\n\u001B[0m20:14:08.657006 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x105e737a0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x106351df0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1063507a0>]}\n\u001B[0m20:14:08.657160 [debug] [MainThread]: Flushing usage events\n\u001B[0m20:14:09.215905 [debug] [MainThread]: An error was encountered while trying to flush usage events\n
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/logs/dbt.log b/logs/dbt.log
--- a/logs/dbt.log	(revision 7d2551e81ad0ec7c8c69786e0033fa9403262e78)
+++ b/logs/dbt.log	(date 1742318464510)
@@ -108,3 +108,35 @@
 [0m20:14:08.657006 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x105e737a0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x106351df0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1063507a0>]}
 [0m20:14:08.657160 [debug] [MainThread]: Flushing usage events
 [0m20:14:09.215905 [debug] [MainThread]: An error was encountered while trying to flush usage events
+[0m14:18:56.355658 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x113557230>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x112c94ad0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x112c958b0>]}
+
+
+============================== 14:18:56.362100 | c0f2f549-531c-477d-97bc-6d8c64c02eb1 ==============================
+[0m14:18:56.362100 [info ] [MainThread]: Running with dbt=1.9.3
+[0m14:18:56.362466 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'version_check': 'True', 'fail_fast': 'False', 'log_path': 'logs', 'profiles_dir': '/Users/insider/.dbt', 'debug': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'False', 'quiet': 'False', 'no_print': 'None', 'log_format': 'default', 'introspect': 'True', 'static_parser': 'True', 'invocation_command': 'dbt run --select logs transformations_ccms', 'target_path': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'send_anonymous_usage_stats': 'True'}
+[0m14:18:56.362800 [error] [MainThread]: Encountered an error:
+Runtime Error
+  No dbt_project.yml found at expected path /Users/insider/Documents/InsiderProjects/dbtCCMS/dbt_project.yml
+  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
+  
+[0m14:18:56.364738 [debug] [MainThread]: Resource report: {"command_name": "run", "command_success": false, "command_wall_clock_time": 0.10771938, "process_in_blocks": "0", "process_kernel_time": 0.346898, "process_mem_max_rss": "92667904", "process_out_blocks": "0", "process_user_time": 1.029266}
+[0m14:18:56.365102 [debug] [MainThread]: Command `dbt run` failed at 14:18:56.365034 after 0.11 seconds
+[0m14:18:56.365356 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x113040830>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x114335be0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x112c94ad0>]}
+[0m14:18:56.365565 [debug] [MainThread]: Flushing usage events
+[0m14:18:57.695588 [debug] [MainThread]: An error was encountered while trying to flush usage events
+[0m14:21:03.935846 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1063e0830>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x10663e060>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1067a0110>]}
+
+
+============================== 14:21:03.939222 | 03232b9a-e316-415e-9364-f8f3db57bf0a ==============================
+[0m14:21:03.939222 [info ] [MainThread]: Running with dbt=1.9.3
+[0m14:21:03.939548 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': '/Users/insider/.dbt', 'fail_fast': 'False', 'debug': 'False', 'log_path': 'logs', 'version_check': 'True', 'warn_error': 'None', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'False', 'log_format': 'default', 'introspect': 'True', 'static_parser': 'True', 'invocation_command': 'dbt run --select logs transformations_ccms from staging_briefings', 'target_path': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'send_anonymous_usage_stats': 'True'}
+[0m14:21:03.939867 [error] [MainThread]: Encountered an error:
+Runtime Error
+  No dbt_project.yml found at expected path /Users/insider/Documents/InsiderProjects/dbtCCMS/dbt_project.yml
+  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
+  
+[0m14:21:03.941912 [debug] [MainThread]: Resource report: {"command_name": "run", "command_success": false, "command_wall_clock_time": 0.07023175, "process_in_blocks": "0", "process_kernel_time": 0.170022, "process_mem_max_rss": "92258304", "process_out_blocks": "0", "process_user_time": 0.616966}
+[0m14:21:03.942173 [debug] [MainThread]: Command `dbt run` failed at 14:21:03.942118 after 0.07 seconds
+[0m14:21:03.942363 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1061c4740>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1063e0830>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x10639b830>]}
+[0m14:21:03.942524 [debug] [MainThread]: Flushing usage events
+[0m14:21:04.509468 [debug] [MainThread]: An error was encountered while trying to flush usage events
